### ISSUE TITLE
isotime() or fromisoformat() is not removing T

### ISSUE THREAD

**Issue by thomasmontoya123** [thomasmontoya123/AirBnB_clone#2]
`"User.d74d0778-defe-4eb5-b56a-bd1439663321": {"id": "d74d0778-defe-4eb5-b56a-bd1439663321", "created_at": "2019-11-10T11:24:31.962515", "updated_at": "2019-11-10T11:24:31.962548",`

**Comment by guxal** [comment]
in this case if it must be saved with the T since it is only deleted at the time of converting an object again
